# Generated by Django 5.0.7 on 2024-07-19 00:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_chapter_pagragraph_translation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="created_at",
        ),
    ]
