# Generated by Django 5.0.7 on 2024-07-19 01:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_chapter_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagragraph",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="pagragraph",
            name="title",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="title",
        ),
    ]
