# Generated by Django 5.0.7 on 2024-07-19 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_pagragraph_created_at_remove_pagragraph_title_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pagragraph",
            new_name="Paragraph",
        ),
    ]
